name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Give workflow the least privilege needed for dependency submission
permissions:
  contents: write    # required to POST dependency-graph snapshots
  # (other permissions default to read)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 19
        uses: actions/setup-java@v4
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: maven,
          server-id: github
          settings-path: ${{ github.workspace }}/.m2

      - name: Build with Maven
        run: mvn clean install
        
      - name: Deploy to GitHub Packages
        run: mvn deploy
        env:
          MAVEN_USERNAME: ${{ github.repository_owner }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

      # Only run dependency submission on pushes to avoid read-only GITHUB_TOKEN on fork PRs
      - name: Update dependency graph
        if: github.event_name == 'push'
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
